### ISSUE TITLE
Merging corrections to the simulator from the refactor branch

### ISSUE THREAD

**Issue by pasha-ponomarenko** [SuperDARN/rst#11]
As I am still pretty much a dummy with github, can anyone help me to merge these changes form the refactor branch into the main obne? 
https://github.com/SuperDARN/rst/commit/5035d30d9dc09413eb2e5e2dfb36369b627da8f4
These changes have been tested awhile ago, but I have not managed to merge them properly...

**Comment by egthomas** [comment]
Is this the only commit from the refactor branch that you intended to merge?  Or will others be merged eventually as well?

**Comment by ksterne** [comment]
It seems as though @kkotyk, made the most of the commits in the `feature/refactorfitacf` branch.  Would he be able to lead the pull request?  If this pull request isn't merging correctly due to my commit a week or two ago, we can forgo that with what is in the currently develop branch.

**Comment by kkotyk** [comment]
Can we merge that whole branch Pasha or just that one commit?

**Comment by pasha-ponomarenko** [comment]
Just this one please.

Cheers,
Pasha

Sent from my Sony Xperia™ smartphone

---- kkotyk wrote ----


Can we merge that whole branch Pasha or just that one commit?

**Comment by kkotyk** [comment]
I need permissions to be able to create branches and perform pushes.

**Comment by egthomas** [comment]
You should have a pending invitation to join the SuperDARN organization with write privileges for this repository.

**Comment by kkotyk** [comment]
I double checked my notifications and emails and I don't see anything. Can you resend it at all?

**Comment by egthomas** [comment]
Closing this issue as the pull request (#19) was approved and merged.
