### ISSUE TITLE
usr directory

### ISSUE THREAD

**Issue by egthomas** [SuperDARN/rst#14]
Is there any need to keep a separate usr/ directory?  With the removal of the ROS software, it seems like the remaining contents could be easily shifted from usr/codebase/superdarn to codebase/superdarn without much problem.  That would be one less seemingly redundant directory living in the rstpath.

**Comment by kkotyk** [comment]
I would agree with this.

**Comment by ksterne** [comment]
I think we've largely cleaned this up now as there isn't a usr directory with the merge of #18.

**Comment by egthomas** [comment]
Yep, closing issue.
