### ISSUE TITLE
Spectral width w_l negative?

### ISSUE THREAD

**Issue by ksterne** [SuperDARN/rst#160]
Hey all, this is probably one of those things where it would be good to have a guide describing what each of the variables means in each of our data products.  Maybe one exists, and if so, maybe someone can point me to it.  But our students were working here and noticed that there's a significant amount of spectral width (Lorentzian fit), w_l, values in fitacf files that are negative.  Is this something that's supposed to be and if so, can someone give some meaning to why a spectral width would be negative and not positive?  Does it have something to do with signals being reversed from some expected response in the frequency domain?

To give an example, we're looking at 20180207.00*cvw* data that a printrec output from `davitpy` can be seen below:

```
2018-02-07  00:01:00  Christmas Valley West fitacf
bmnum = 23  tfreq = 14701  sky_noise_lev = 11  search_noise_lev = 17  xcf = 1  scan = 1
npnts = 8  nrang = 100  channel = 0  cpid = 151
gate range pwr_0 / pwr_l      vel gsf  vel_err  width_l  geo_lat  geo_lon  geo_azm  mag_lat  mag_lon  mag_azm
  39  1935  -5.0 / 7.8        8.4   1      2.9      7.1    58.79  -111.91    21.49    66.16   -49.83    14.43
  43  2115 -50.0 / 5.2       12.2   1      5.5      5.3    60.28  -110.71    22.93    67.73   -48.74    15.90
  44  2160 -50.0 / 8.4        7.4   1      2.7      9.4    60.66  -110.39    23.31    68.13   -48.45    16.30
  45  2205  -6.4 / 12.6      -4.5   1      1.9      3.9    61.03  -110.06    23.69    68.52   -48.13    16.70
  46  2250  -8.5 / 9.9       12.4   1      4.2     16.9    61.40  -109.72    24.09    68.91   -47.81    17.11
  47  2295  -2.4 / 13.0      -3.7   1      0.9      1.7    61.76  -109.37    24.49    69.30   -47.47    17.53
  48  2340  -5.0 / 8.2       -5.5   1      2.5     13.2    62.13  -109.02    24.90    69.68   -47.12    17.97
  50  2430 -50.0 / 5.6       -4.4   1      4.0     -0.5    62.86  -108.27    25.76    70.46   -46.36    18.89

2018-02-07  00:01:02  Christmas Valley West fitacf
bmnum = 22  tfreq = 14710  sky_noise_lev = 10  search_noise_lev = 18  xcf = 1  scan = 0
npnts = 8  nrang = 100  channel = 0  cpid = 151
gate range pwr_0 / pwr_l      vel gsf  vel_err  width_l  geo_lat  geo_lon  geo_azm  mag_lat  mag_lon  mag_azm
  40  1980  -4.4 / 4.6        6.0   1      6.0     53.3    59.49  -113.34    17.34    66.59   -51.94     9.64
  44  2160  -5.8 / 7.7       -4.5   1      4.6    -18.3    61.03  -112.34    18.56    68.19   -51.20    10.76
  45  2205  -1.3 / 12.6      -2.3   1      2.0      0.8    61.41  -112.07    18.88    68.58   -51.00    11.06
  46  2250  -7.8 / 7.7      -12.0   1      2.8     14.7    61.79  -111.80    19.21    68.98   -50.78    11.36
  47  2295  -4.4 / 18.1      -2.2   1      0.9     -0.3    62.17  -111.51    19.55    69.37   -50.55    11.67
  48  2340  -7.8 / 20.0      -4.7   1      0.8      0.2    62.55  -111.22    19.90    69.77   -50.32    11.99
  49  2385  -3.4 / 9.2       -6.4   1      3.0    -13.9    62.93  -110.92    20.25    70.16   -50.07    12.32
  51  2475  -7.8 / 3.5        4.0   1      8.8     50.1    63.69  -110.29    20.99    70.95   -49.55    13.01

```

**Comment by pasha-ponomarenko** [comment]
@ksterne, this is a well-know issue with the exponential fit. Just a few weejks ago Evan asked the same question. The bulk of the negative spectral widths occurs in the ground scatter for which the power vs lag dependence is very flat so that due to fitting errors it might be either slightly begative or slightly positive. It just means that the width estimate is of the same order as its fitting error.

**Comment by pasha-ponomarenko** [comment]
There should be " its fitted slope might be " instead of "it might be".

**Comment by pasha-ponomarenko** [comment]
The only reference to the fitted data products which I am aware of is the old Rob's description (I copied it as PDF and stored here  at https://homepage.usask.ca/~pbp672/DAWG.html in "Supplementary materials" as "FIT data format"

**Comment by egthomas** [comment]
@pasha-ponomarenko the source for that page is actually included in the RST; the html version can be viewed here:  https://superdarn.github.io/rst/superdarn/src.doc/rfc/0009.html

**Comment by pasha-ponomarenko** [comment]
Thanks, Evan, I was pretty sure it is somewhere there!

**Comment by ksterne** [comment]
Mmmm, we'll that's a start I guess.  Though it would be good to put a little bit more onto the description.  What does positive/negative convention mean?  Are there limits like must always be positive?  Or any error codes?  One might even have some fun trying to define "scan" ;).

**Comment by sshepherd** [comment]
A scan is just a sequence of beam soundings that repeat.

**Comment by pasha-ponomarenko** [comment]
I thiought I had Kile's tutorial from early 2000s, but apparently I hadn't, so I added it to the "Supplementary materials" list. Here is its direct link:
https://homepage.usask.ca/~pbp672/Kile.pdf
