### ISSUE TITLE
Wrong documentation for rawacf file

### ISSUE THREAD

**Issue by kkotyk** [SuperDARN/rst#194]
Provided the documentation that @egthomas is hosting at https://superdarn.github.io/rst/superdarn/src.doc/rfc/0008.html is up to date, the type for the acfd and xcfd array is wrong I think. I think these are actually floats instead of shorts.

**Comment by pasha-ponomarenko** [comment]
> History
--
2007/03/26  Revision incorporating origin and beam azimuth. 
2004/07/29  Initial Revision.

I guess the document has been written before switching from *.dat to *.rawacf
