### ISSUE TITLE
Folder not found Segfualt 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#207]
While testing PR #204, I noticed when I used the `-path` option with `map_plot` I got a `segfault` if the directory did not exist. 

Possible solutions:
1. create the directory if it does not exist 
2. Print an error that the "Folder does not exist"

Otherwise, this segfault is miss leading about what is wrong and poor practice.

**Comment by egthomas** [comment]
Nice catch.  My vote would be to print an error and exit rather than try to create a directory (which could run into other permission issues).

**Comment by mts299** [comment]
@egthomas This was resolved in #204 correct? 
If so then we should close the issue :+1:

**Comment by egthomas** [comment]
@mts299 no, I don't think that pull request modified any of the plotting code.

**Comment by ksterne** [comment]
@mts299, I know you're out here so I'll close this since it was solved in #262.
