### ISSUE TITLE
time plot auto-adjusting time domain 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#214]
While testing #209 I noticed the time domain does not auto adjust for a given file. So when I input a 2-hour file it gives me a 24 hr plot: 
![time_3_0_sas](https://user-images.githubusercontent.com/6520530/51768606-61dc5380-20a6-11e9-80fd-d9e4d74b9803.png)

A possible enhancement is for it to adjust the time scale based on the start time and end time of the file.

**Comment by asreimer** [comment]
Addressed by #235
