### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by asreimer** [SuperDARN/rst#215]
It's been awhile coming, but I've created a draft installation guide here: https://github.com/SuperDARN/rst/wiki/Installation-Guide. This was suggested in previous issues here.

The intention of this wiki page is to replace the OS specific notes in the "Installation Notes" in the RST README.md, as per the discussion in #164. I think we decided that the wiki is a better place for this because updating the installation documentation shouldn't need to be done with pull requests.

Once people are happy with the wiki page, the README.md can be updated to point to it. The README.md will still have some installation information, but will be general and not really OS specific.

From what I can see, here are the things left to add to the wiki Installation Guide:
- [x] Ubuntu 18.04 LTS installation instructions (should be similar to previous versions)
- [ ] macOS Conda installation instructions
- [x] macOS Homebrew installation instructions
- [ ] Windows 10 installation instructions
- [ ] macOS instructions for different versions?

It is possible to install RST without using macports or homebrew. This summer I installed RST on a student's macbook using only conda. I have an old macbook that friend gave me, so I'm hoping I can get it up and running and test the conda-only installation process. After that, I'll explore the windows installation process.

Finally, @aburrell, do you know if the macports installation instructions are dependent on precise macOS version? Are the instructions the same on High Sierra (10.13) compared to Sierra (10.12)? Sierra is the current version discussed in the RST installation notes.

Note: for windows, I've found this which might be helpful: https://github.com/esa/auromat/blob/master/README.rst

**Comment by mts299** [comment]
This is an interesting choice on how to use the wiki. Typically the README will handle all installation information as it is the first place a user goes and reads as suggested here https://guides.github.com/features/wikis/

I would imagine the wiki containing release notes, choices made in the software (like why DMAP format files) and maybe some examples or some information on the software, like scipy does https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate
¯\_(ツ)_/¯

**Comment by asreimer** [comment]
@mts299 I have no strong opinions either way. I tried adding additional installation information to the README.md in #164 and it was suggested we make it a wiki page.

It would be really nice if we could agree to some standards so that people can do things "properly" the first time. Nice thing here is that the wiki page uses the same markdown as the README.md file.

**Comment by mts299** [comment]
@asreimer I understand. I was just pointing out a guideline stated by github and followed by other repositories. But if this is the standard or preferred for us, I am okay with it. 

Just thought I would point it out if anyone was interested in what github standards are.

**Comment by pasha-ponomarenko** [comment]
I might have lost some technical details here, but for me it seems only logical to have tthe installation readme document distributed with the package and be available fron the distribution location. 
With respect to the table, don't the "normal" Linux installations include most of these packages by default? I am pretty sure that gcc is there...

**Comment by asreimer** [comment]
@pasha-ponomarenko no, not all linux distros come with gcc installed by default. Most development tools aren't installed because it isn't expected that most users are going to be developers.

**Comment by asreimer** [comment]
@pasha-ponomarenko if you read the post at the top of this issue, I said the intention of the wiki "Installation Guide" page is to provide step-by-step OS specific installation instructions, whereas the README would have general installation instructions. If we want to put everything back in to the README.md file, that's fine with me, except that I think the point @egthomas was making in #164 is that the README is becoming a huge monster and being a bit abused if we throw everything in it.

If you want to distributed step-by-step OS specific instructions with RST instead of on the wiki, a better solution might be to include an INSTALLATION file in the repo. This is pretty common practice as well.

As I said before, it would really streamline the process if this project had some developer contribution standards that were agreed upon before people started making contributions. Not too big of a deal for this particular issue, but worth thinking about.

I'm just going to keep adding installation information to the wiki and let you guys sort out where to put it.

**Comment by pasha-ponomarenko** [comment]
@asreimer, thanks for the clarification...

**Comment by billetd** [comment]
I've done the Mac Homebrew installation a few times, so I can fill in those commands

**Comment by asreimer** [comment]
Any objections to creating an INSTALLATION.md file PR? This would basically be a copy paste of the contents in the Wiki page, but would have the benefit of being shipped with RST releases. It could also be slurped into a readthedocs page trivially. Thoughts @egthomas, @mts299?

Note that again, someone is trying to provide readme installation instructions (#227), reminding us that we need to do something. If I don't hear back by the weekend, I'll just make the PR.

**Comment by billetd** [comment]
I took a look at the installation process again today on clean Ubuntu and OSX machines, and saw a couple of issues which occurred in both before getting to fully compile.

1 - Pretty minor, but the default X11 directory in base.bash (/rst/.profile/) is outdated. The install instructions do ask the user to check this directory is correct, but it would cause one less problem if it was updated to where all the major package downloaders (macports, brew, etc) put it:
`/usr/x11a ---> /usr/lib/x11`

2 - CDF is marked optional in install guide/readme, but make.code will fail to compile if it’s not installed in many instances. The first in simply finding the library, but also in many places where the CDF is linked to RST code (such as in dmaptocdf and istp_plot makefiles) via the –lcdf flag. I remember a brief discussion of CDF inclusion in the working group meeting – it seems like there is still a good portion of code still depending on the link being there, even if the user might not take advantage of it. I’m not sure how to do the surgery on that, maybe best to just make CDF a requirement for now?

Also @asreimer, I agree with your above comment. The installation guide on the wiki is at least more thorough (i.e. it has instructions for downloading dependencies + more). It really should be front and centre.

**Comment by mts299** [comment]
@billetd I started porting over the wikki install guide to read the docs and cleaning it up. I am hoping to put the readthedocs on the README.md next to the current rst documentation to start the movement towards that platform. 

Would you be interested in contributing there? It would help me and avoid parallel documentation.

**Comment by asreimer** [comment]
The readthedocs page is looking fantastic and is accomplishing everything we wanted the wiki page to accomplish.

Given:
1) the installation instructions on the readthedocs page is located in docs/user_guide
2) the source code for that page is written in markdown and therefore easily readable offline in a text editor
3) the source code for that page is can be built offline using the python sphinx package

I propose we use the readthedocs page to handle installation instructions. If this is agreed upon, then we need to:
1) Edit the `README.md` file to point users to the installation documentation in `docs/user_guide`
2) Add the CentOS installation instructions from #227 to the `docs/user_guide` branch

Yes?

**Comment by mts299** [comment]
Pushed @asreimer :) Thank you for helping out. 

If anyone wants to see what @asreimer was mentioning:
https://radar-software-toolkit-rst.readthedocs.io/en/latest/

I would like to make a PR soon to add this to the `README.md` so users can look here for more detailed install instructions and the RST howto's @ecbland made. 

The installation guide for Mac still needs to be written and of course proofreading :)

**Comment by mts299** [comment]
@asreimer and @billetd where are we at on this? 

@billetd added the mac installation instructions :+1:  

If we are good to go I will make a PR on the documentation :)

**Comment by asreimer** [comment]
I'm still looking at some things. I really just need to spend a couple hours looking at this. I think I can do that on Thursday (2 days from now). Can we wait and check in on Friday?

**Comment by billetd** [comment]
The Mac install goes largely similar to linux once the dependencies are in place, so I'm happy for the PR. I am however a bit wary that the spread of OSX versions people tend to use is normally quite large - so we might be able to anticipate version issues, especially when it comes to Xcode.

**Comment by asreimer** [comment]
I was able to have a look and it all looks pretty awesome to me. Nice work @mts299 and @billetd!

I was not able to test the conda based macOS installation. I'm having troubles accessing my mac system remotely, so that will just have to be added later.

Time to make a PR and close this issue?

**Comment by mts299** [comment]
Sounds good to me 👍

The only thing to add now is add the read the docs link to the README and just mention it only supports installation instructions and RST how-to's.

**Comment by mts299** [comment]
Closing this issue and we can start a new issue for 
Installation for Windows and another issue for other install information for Mac when you have time to look into this again @asreimer or anyone else that works with those machines.
