### ISSUE TITLE
Docker files

### ISSUE THREAD

**Issue by kkotyk** [SuperDARN/rst#26]
I'm working on creating Docker(https://www.docker.com/what-docker) files so that we can have container images to be able to quickly test installs and stuff in a virtualized environment. I'm just wondering where to keep the files. I think it would be a good idea to start a new repo so that we can create and modify images as we see fit.

**Comment by kkotyk** [comment]
pinging @egthomas. I've got Docker files made up for both Ubuntu and OpenSUSE. They are working quite nicely.

**Comment by egthomas** [comment]
I don't see any problem with putting these in a separate repository here on the superdarn organization.  Do you have permissions to create a new repository?  (I need to do some more reading to understand how these docker files work)

**Comment by kkotyk** [comment]
@egthomas I dont have permissions to create a repo.

**Comment by egthomas** [comment]
ok that should be fixed, let me know if you still don't have permission

**Comment by egthomas** [comment]
Do we need any additional docker files?  I could try creating one more for Mint.

**Comment by kkotyk** [comment]
Up to you I guess. If the Mint install process isn't too complicated then maybe its a good idea.

**Comment by egthomas** [comment]
Probably not going to get to that Mint docker file after all so I think we're done here.  @kkotyk - agreed we can close this issue?

**Comment by kkotyk** [comment]
Agreed.
