### ISSUE TITLE
Jiamusi Radar

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#263]
Maybe one more thing to consider for the next release is adding Jiamusi Radar to the radar.dat file so we can process the data. Currently, I cannot process it to FITACF because of the commission issue that was brought up before #239. 

However, this data has been cleared and now part of the data distribution. 

Or if changing radar.dat file is out of DAWG scope, could we consider a warning message now so that users can process commissioned data that is in the distribution?

**Comment by ksterne** [comment]
It's still not been clear to me when the commission date is and/or the acceptance by the PIs.  I think there was a discussion about this at the AGU meeting, but I haven't followed up with my PI on it.  I'll try to do that here soon.

**Comment by mts299** [comment]
Okay, if not can we look at making a warning message and not stop the ability to process the data?

**Comment by ecbland** [comment]
@ksterne Any update on this? I noticed that the JME hardware file is already in the `hdw.dat` repo, so we should copy that over to RST. We still need to find out the start date to use in the `radar.dat` file.

**Comment by ksterne** [comment]
I got word back and got this info in #276.  So this is another one that I think I'd leave to @mts299 to close, but I will for now.  Marina, feel free to open it back up or the other one if needed.
