### ISSUE TITLE
PR/Issue Templates

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#295]
Hey, 

I made some PR templates for pyDARN and soon some issues templates. Wondering if this is something we would like to do? 

Take a look at pyDARN PR # 44 (https://github.com/SuperDARN/pydarn/pull/44); if yes, then I can either copy over any those templates (if you like them) or make some new ones here, and we can create a PR as well to allow for more suggestions on the wording and whatnot. 

Side note: if you do like them and checked them out on pyDARN, please provide feedback there as well :p

**Comment by ecbland** [comment]
Closing this issue now that #298 and #299 have been merged. Thanks @mts299!
