### ISSUE TITLE
Dat to RAWACF issue?

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#303]
Once again I am regenerating rawacf -> fitacf 2.5 -> map files for Kathryn/SuperDARN community and as I finish the more recent years, I am wondering if my dat to rawacf files are safe to convert to fitacf 2.5/map files? 

@egthomas in the DDWG meeting you mentioned a potential issue with this conversion. Could you please elaborate more? 
If this is an issue/bug can we make it a high priority to fix as well?

**Comment by ecbland** [comment]
Just to add to this, @kevinkrieger reached out to me & @ksterne last Friday asking if the DAWG can help develop a tool to check dat files and the dat->rawacf conversion. We haven't discussed this properly yet, but this might be a good opportunity for DAWG & DDWG to work together :)

**Comment by mts299** [comment]
I would be more than willing to help out as we will need to verify these files to be able to put them in an archive on FRDR which the PI's approved. One thing to consider if this would be an RST task or should we look at pyDARN to help with this?

**Comment by mts299** [comment]
@egthomas comment?

**Comment by ksterne** [comment]
Hey @mts299, I know @egthomas is out for the better part of the next month (I think) so I wouldn't expect a comment quickly.  There's some errors I've noticed on `dattorawacf` but I haven't been able to capture it.  I can try to expand on it sometime in the future, but not today.

**Comment by mts299** [comment]
Okay my bad so his activity the other day and week so thought he was back.

**Comment by egthomas** [comment]
Sorry, like @ksterne said I'm currently out of the office on leave and was just trying to help with the release a few days ago.

I don't have any concerns with the current state of the `dattorawacf` conversion process in terms of software.  The issue I raised during one of the WG meetings (can't remember which one) was probably related to the data mirror / distribution aspect and keeping the converted rawacf files in separate directories from the original rawacf files produced on-site.

There may be an inconsistency in how we handle the `origin.code` parameter when executing `make_raw` or `make_fit` compared to `dattorawacf` or `fittofitacf`, but that is probably out of scope for this particular issue.

**Comment by mts299** [comment]
Sounds good I will close this issue and pass it onto DDWG for checking files made by `dattorawacf` to determine if need to be regenerated.
