### ISSUE TITLE
To bug or not to bug in time_plot swap

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#348]
In `time_plot` there is some code to swap variables but it doesn't. Unsure if this is a bug or not? 

https://github.com/SuperDARN/rst/blob/0aa1fffed4cc48c1eb6372dfc9effa688af95624/codebase/superdarn/src.bin/tk/plot/time_plot.1.8/time_plot.c#L1379-L1381

**Comment by egthomas** [comment]
It looks like this is meant to handle range-time plots in geographic or magnetic coordinates where the radar beam may be crossing over the pole or is zonally-directed, ie the magnitude of latitudes increase and then decrease with each range cell along the beam.  So the code is looking for whether it needs to swap the top and bottom latitude values when drawing the colored cell.  If that is the purpose, then yes, it seems like the code should be swapping the `tlat` and `blat` variables.
