### ISSUE TITLE
Scalars table in Grid documentation broken?

### ISSUE THREAD

**Issue by egthomas** [SuperDARN/rst#352]
The markdown for the "Scalars" table in the read-the-docs Grid format documentation is not appearing correctly in my browser:

https://radar-software-toolkit-rst.readthedocs.io/en/latest/references/general/grid/

When I copy the markdown text into this issue field it appears correctly, but on my screen it appears more like this:

![grid_docs](https://user-images.githubusercontent.com/1869073/96498854-9dc03080-121a-11eb-95da-a6f9ac6d948c.png)

**Comment by ecbland** [comment]
Fixed with #354. Thanks @egthomas and @mts299 👍
