### ISSUE TITLE
field_plot does not plot Antarctica coastline

### ISSUE THREAD

**Issue by ecbland** [SuperDARN/rst#353]
While testing #335, I noticed that `field_plot` does not plot the Antarctica coastline when the `-coast` option is provided. 

Example: 
`field_plot -x -coast -fan -keyp -v -tl 60 -grd -latmin 20 20180601.1001.00.zho.fitacf`

The filled coastline option (`-fcoast`) works fine.

**Comment by mts299** [comment]
Poor South
