### ISSUE TITLE
RST 4.5

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#355]
Do we want to create a release branch for RST 4.5?

**Comment by ksterne** [comment]
I agree here. I'll try to capture some PRs that are pretty close that we can knock out here quickly to start up our minor release processes.

**Comment by ecbland** [comment]
I will test #337 and #354 tomorrow. I would appreciate some help though, especially with #337 since that one may have different behaviour across platforms.

**Comment by ksterne** [comment]
Sorry, there's also this open issue that we could continue discussion as we wrap up steps for the new release.

**Comment by ecbland** [comment]
@ksterne The release is now available on zenodo, and I will email the darn-users mailing list later today. So I think we can close this
