### ISSUE TITLE
Elv_low Elv_high in Fitacf 3.0 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#357]
So I left the `elv_low` and `elv_high` the same as Pasha implemented them as (not the same as FITACF 2.5, @ecbland if you can explain better please do so!) in PR #356; however, because they have 2 meanings based on the algorithm picked and may not be aware to the user that the meanings have changed between versions. 

I am wondering if we want to convert FITACF 3.0 `elv_low` and `elv_high` back to the meaning of what FITACF 2.5 set it as and ask DSWG about creating 2 new FITACF fields for FITACFs 3.0 current `elv_low` and `elv_high`?

Please do not ask me specifics as I don't really know much except what is in the code.  However, suggestive ideas and solutions are most encouraged and what actions to take next on this given problem.  

-----

EDIT by @ecbland :

FITACF 2.5 (documented [here](https://radar-software-toolkit-rst.readthedocs.io/en/latest/references/general/fitacf/))
- `elv` is the elevation angle calculated from the fitted phase
- `elv_high` is the upper estimate of the elevation angle
- `elv_low` is the lower estimate of the elevation angle

FITACF 3.0 (documented [here](https://superdarn.github.io/dawg/files/sup_material/FITACF3_release_notes.pdf))
- `elv` is the elevation angle calculated from the lag zero phase of the ACF
- `elv_high` is the elevation angle calculated from the fitted phase (cf. FITACF 2.5 `elv`)
- `elv_low` is the least square error

**Comment by ecbland** [comment]
Re-opening this issue since we are waiting for PI input. (I think there was some confusion here with #410, which is already closed)

**Comment by mts299** [comment]
Woops sorry closed the  wrong issue :p

**Comment by ecbland** [comment]
Update: the PIs approved [our suggestion](https://superdarn.github.io/dawg/reports/202102/#fitacf3-elevation-fields) to add some new fields to the fitacf format at their meeting in November 2021. I already started the coding to implement this change...I'll make a PR when it's ready.
