### ISSUE TITLE
TODO: change old LGPL disclaimer to GPL

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#394]
After the meeting and well-made documentation on the copyrighting and licensing in RST by @ecbland we now need to move our potentially mistaken LGPL disclaimers to GPL.

**Comment by ecbland** [comment]
Here's the link to the updated documentation on licensing & copyright: https://radar-software-toolkit-rst.readthedocs.io/en/develop/developers_guide/copyright_license/
(I had to clear my browser's cache before the updates showed up)

**Comment by ecbland** [comment]
Thanks @mts299 for all your work helping us to understand copyright & licensing over the last few years, and for adding the necessary changes to the license notices throughout RST :100:
