### ISSUE TITLE
fitacfT.2.4 vs fitacf.2.5 libraries

### ISSUE THREAD

**Issue by egthomas** [SuperDARN/rst#41]
Does anyone know the difference between the fitacfT.2.4 and fitacf.2.5 libraries?  Do we need to keep both of them?  It looks like the files in the fitacfT.2.4 directory may have been copied from an older version of the RST (maybe 3.2?) into the VT RST at some point.  @pasha-ponomarenko ?

**Comment by egthomas** [comment]
@pasha-ponomarenko - any ideas here?  You mentioned you were trying to collect all older versions of FITACF, so do you think we need to keep distributing this copy of fitacf.2.4 with the RST?

**Comment by pasha-ponomarenko** [comment]
The general idea is (or at least was) that anyone should be able to re-process raw data with any of the previous versions of FITACF without much trouble. For example, FITACF3 does not generate velocities, spectral width and power and their respective errors from XCFs, but the older versions do, and if someone fancies these obscure parameters, then he/she should be able to obtain them without troubling others. 

So, I am not sure what is the technically optimal solution to this, i.e. if we need to keep several versions in the src directiry or store them somewhere else.

**Comment by egthomas** [comment]
Would it be possible to have a separate git repository (kind of like you've done with fitacf.3.0 on the SuperDARNCanada page) where all of the different versions of FITACF live?  The current default (2.5? eventually 3.0?) would then be the only version distributed with the actual RST, but users could still go and grab the "stand-alone" versions if they prefer.

**Comment by kkotyk** [comment]
@egthomas Yes this could be done if the group wants. The only issue I see here that will be tough to get around is if there are dependency conflicts for make_fit between the different versions of RST.

**Comment by egthomas** [comment]
Yeah, maintaining compatibility would be a pain.  But we'll still have that issue if we keep the previous version of fitacf in the RST each time a newer version is introduced, right?

**Comment by pasha-ponomarenko** [comment]
By the way, does anyone know what the capital T in FITACF2.4 means?

**Comment by egthomas** [comment]
No idea - I think AJ or someone else at VT may have introduced it somewhere between RST 3.3 and VTRST3.5.

**Comment by kkotyk** [comment]
@egthomas Yes this is the case. I'm just thinking about potential difficulties as I have no idea what to expect from the earlier versions, especially around version 1 era. Would anyone have version 1 of RST and fitacf?

**Comment by egthomas** [comment]
Doubtful, as that code must be well over a decade old by now.  You could try a darn-users email blast (which tends to get mixed results) or asking around at the workshop in June.

**Comment by ksterne** [comment]
Instead of stand alone repos, could there be a fitacf wrapper code that when execute `make_fit` there are options on which version to call up?  Maybe this makes the binary larger.  But thinking something like:

`make_fit` -> latest fitacf
`make_fit --version 2.5` -> fitacf.2.5
`make_fit --version 2.4` -> fitacf.2.4

and so on.  Again, this is just a high-level vision; I'm not sure if it's easy to implement this or not.

**Comment by egthomas** [comment]
see #58 - turns out the fitacfT.2.4 is used solely for the `test_fitacf` tool written by AJ.
