### ISSUE TITLE
Extracting latitude and longitude information from fitacf data

### ISSUE THREAD

**Issue by TsigeA** [SuperDARN/rst#418]
Hi, I need help extracting information from a '.fitacf' data; power, velocity, spectral width, latitude and longitude.
I have a '.dat' file which I convert to '.fitacf' data by following the procedure listed here  https://radar-software-toolkit-rst.readthedocs.io/en/latest/user_guide/make_fit/.
Then using dmapdump -d command, I can print the data values of the array variables and save them in a '.txt' file.
From this file, I can see the power, velocity and other information, but I can't find the geomagnetic or magnetic latitudes and longitudes.
I am not sure if this is the right way to get such kind of data since it is my first time working with '.fitacf' data. I usually use the print fit record from the VT superDARN website.

Any suggestion will be helpful. Thank you!

**Comment by aburrell** [comment]
Hi @TsigeA!  Welcome to the wonderful world of FitACF data :) The information you're looking for isn't available at this level of processing.  The FitACF data doesn't have latitude and longitude coordinates, everything in this file is still in radar coordinates.  To calculate the latitude and longitude, you need to use either a virtual height model or the elevation angles to determine the location.  This information is first calculated in the grid files.  You can get from FitACF to grid following this example: https://radar-software-toolkit-rst.readthedocs.io/en/latest/user_guide/make_grid/

**Comment by mts299** [comment]
Hi @TsigeA 

Fitacf does not have geomagnetic or magnetic latitudes and longitudes.
You can get them by converting your fitacf file to grid files using `make_grid`: https://radar-software-toolkit-rst.readthedocs.io/en/latest/user_guide/make_grid/

Then use `dmapdump -d` again which should also have velocity, power, and spectral width values if you include `-xtd` with make_grid. 

Side note: pyDARN will be featuring a new feature to generate the longitude and latitude for fitacf files just will not be stored in them.
