### ISSUE TITLE
dattodmap intt issue

### ISSUE THREAD

**Issue by egthomas** [SuperDARN/rst#469]
There appears to be an error when converting the `intt` value for `.dat`-format files to `dmap`-format when using the `datdump` binary.  For example, here is the output from `datdump` (first record of `1995092404t.dat`):

```
    int "intt" = 19660814
```

while here is the output from `dattorawacf` and then `dmapdump`:

```
    short   "intt.sc" = 14
```

There may need to be a change at this line

https://github.com/SuperDARN/rst/blob/c9345ca78fe88c0279dc09fbb9eaf91da512d684/codebase/general/src.lib/dat/src/dattodmap.c#L92

from `DATAINT` to `DATASHORT`, eg

https://github.com/SuperDARN/rst/blob/c9345ca78fe88c0279dc09fbb9eaf91da512d684/codebase/superdarn/src.lib/tk/oldraw.1.16/src/raw.h#L63

**Comment by mts299** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Evan datdump error](https://trello.com/c/YKuXusHP/11-evan-datdump-error)
