### ISSUE TITLE
TDIFF values in FitACF 2.5

### ISSUE THREAD

**Issue by ecbland** [SuperDARN/rst#493]
@egthomas , @ecbland , I was testing utilisation of the two _tdiff_ values for calibrating non-stereo two-channel data and came across an apparent problem.  It seems that there is a mix-up with applying _tdiff_ values to stereo data by FITACF2.5. If I change _tdiff_[0], elevation values  change in both channels but if I change _tdiff_[1], there are no changes in either of them. This problem does not exist for the data processed with FITACF3 when changes in _tdiff_[0] cause changes in channel 1 only, and changes in _tdiff_[1] lead to changes in channel 2 only. Please see attached a stack of PPT slides illustrating this issue. 

[TDIFF misfit for FITACF2.pptx](https://github.com/SuperDARN/rst/files/8347729/TDIFF.misfit.for.FITACF2.pptx)

I used _develop_ branch for this analysis.

I suspect that this issue may be caused by the way tdiff is declared in FitPrm structure (a single value instead of a two-element array), but I can easily be mistaken.

_Originally posted by @pasha-ponomarenko in https://github.com/SuperDARN/rst/issues/455#issuecomment-1078672766_

**Comment by egthomas** [comment]
@pasha-ponomarenko @ecbland thanks for identifying this issue.  I think I have identified the problem - `FitACFMake` is called once by `make_fit` to populate the `FitBlock` structure (with a channel-dependent `tdiff`), but that function never gets called again so the `tdiff` values aren't updated when the record / channel changes.  I'm working on a fix now and hope to have it ready for testing soon.
