### ISSUE TITLE
Twofsound multiple 'channel' data not being processed correctly (example 20161117 CDN data)

### ISSUE THREAD

**Issue by ksterne** [SuperDARN/rst#5]
This is the issue from the old repo (https://github.com/vtsuperdarn/VTRST3.5/issues/25) moved over.  Here I've copy and pasted Kevin Krieger's original post.

For some reason, RST3.5 doesn't process fitacf files correctly for the twofsound data from twofsound.1.04 where the channel parameter is changed to '1' or '2' depending upon which frequency is being transmitted.

Below are plots from davitpy that used fitacfs generated at usask with stk, they seem to have the data plotted. Also attached are plots from Dieter's IDL plotting code written using stk libs, which don't seem to have plotted correctly, for completeness.

![alt text](https://cloud.githubusercontent.com/assets/5935875/22166197/ca98f104-df57-11e6-88b0-749db9ac5d08.png "Logo Title Text 1")
![alt text](https://cloud.githubusercontent.com/assets/5935875/22166200/ca9bd34c-df57-11e6-855c-359ad04280dd.png "Logo Title Text 1")
![alt text](https://cloud.githubusercontent.com/assets/5935875/22166198/ca99ac16-df57-11e6-81c2-0d5ac3bee9cc.png "Logo Title Text 1")
![alt text](https://cloud.githubusercontent.com/assets/5935875/22166199/ca9a2092-df57-11e6-99b0-9b1ed03a241c.png "Logo Title Text 1")

**Comment by pasha-ponomarenko** [comment]
Any news here? I am struggling to find time for looking closer into this issue with three conferences looming in the next 5-6 weeks. In order to be able to have a detailed look I would need to replicate the badlag determination in IDL so that I can easily track what is going on. I will try...

**Comment by ksterne** [comment]
Haven't found the time here either, spent most of the time transitioning over to this repo.  I think the latest thing I need to take a look at is why the receiver blanking isn't being marked.  I've tried taking a look at the cross range interference issue as well, but haven't had a chance to look at it.

**Comment by ksterne** [comment]
Believe this has now been fixed with #57.  Do you believe that's true @pasha-ponomarenko?

**Comment by pasha-ponomarenko** [comment]
I hope so! 
;-)

**Comment by egthomas** [comment]
Ok, closing.

**Comment by egthomas** [comment]
Is it also safe to remove the `bugfix-usask_freq_chan` branch?

**Comment by ksterne** [comment]
Sorry to be slow, but it seems good to remove this branch so I've done so.
