### ISSUE TITLE
IDL FitSeek DLM segmentation fault

### ISSUE THREAD

**Issue by egthomas** [SuperDARN/rst#525]
I'm not sure if this is because I'm using a file with a non-standard control program, but I'm encountering a segmentation fault when trying to use `FitSeek` from within IDL via the DLM (`RawSeek` is working fine, and so are `FitOpen` / `FitRead` / `FitClose`).  Can anyone else replicate this?  This may be my first time trying to use `FitSeek` from within IDL.  Thanks!

**Comment by pasha-ponomarenko** [comment]
@egthomas, I have never used it, sorry!

**Comment by egthomas** [comment]
@pasha-ponomarenko no problem - it ended up being a simple fix!
