### ISSUE TITLE
How are the src and include directories supposed to be laid out in src.lib?

### ISSUE THREAD

**Issue by kkotyk** [SuperDARN/rst#55]
When I look at the src.lib directories, there are headers in both include and src. What headers are supposed to go in each if I am to add a new library?

**Comment by egthomas** [comment]
The header files in the include subdirectory of the src.lib directories are the ones copied into the main include directory of the RST.  So I think the difference may be whether another function outside the library will need that header information.

**Comment by kkotyk** [comment]
Thought so. Ill structure it that way.

**Comment by egthomas** [comment]
Closing this since it looks like you've figured it out.
