### ISSUE TITLE
Issue regarding SuperDARN RST installation

### ISSUE THREAD

**Issue by ArdraRamachandran** [SuperDARN/rst#583]
I am using Ubuntu 22.04 in the system, and I am unable to find an RST installation guide suitable for this distribution. Is that possible to add the Ubuntu 22.04 version to the installation guide?

**Comment by egthomas** [comment]
@ArdraRamachandran the only library dependency that may have changed is needing `libhdf5-dev` instead of `libhdf5-serial-dev`.  Otherwise, the installation steps should still be the same.  Is there a particular issue you're encountering?

**Comment by ArdraRamachandran** [comment]
@egthomas thank you, I successfully completed my installation
