### ISSUE TITLE
Installation for Ubuntu 22.04

### ISSUE THREAD

**Issue by PajNath** [SuperDARN/rst#599]
Hi, I would like to install the SuperDARN/rst on Linux with Ubuntu 22.04 version, can I just follow the guide made for the 20.04 version? Thank you in advance for your help. Regards

**Comment by ecbland** [comment]
Hi @PajNath, it should be fine to follow the instructions for Ubuntu 20.04 - give it a try and let us know if you have any problems

**Comment by egthomas** [comment]
@PajNath I think the only difference is the change from `libhdf5-serial-dev` (Ubuntu 20.04) to `libhdf5-dev` (Ubuntu 22.04) in the list of required libraries.
