### ISSUE TITLE
Changes in IDL paths is not reflected in idl.bash

### ISSUE THREAD

**Issue by pasha-ponomarenko** [SuperDARN/rst#88]

**Comment by pasha-ponomarenko** [comment]
"... are not reflected..."

**Comment by egthomas** [comment]
Could you be a little more specific?  Not sure I understand the issue here.

**Comment by pasha-ponomarenko** [comment]
Look at /rst/.profile/idl.bash on the develop branch. All paths are incorrect:

export IDL_PATH="<IDL_DEFAULT>:+/${RSTPATH}/idl/lib"
export IDL_DLM_PATH="<IDL_DEFAULT>:${RSTPATH}/dlm"
export IDL_STARTUP="${RSTPATH}/idl/startup.pro"

**Comment by egthomas** [comment]
Sorry, I'm still confused.  Which of these is incorrect and what should they be changed to?  At a minimum, the `IDL_PATH` environment variable is going to be unique to each users' IDL installation directory.

**Comment by kkotyk** [comment]
As far as I see there is no longer a idl folder in the top level, so the IDL_STARTUP path doesn't exist. We should maybe add a line to the installation instructions if the IDL_PATH needs to be manually updated.

**Comment by pasha-ponomarenko** [comment]
These paths reflect the old directory structure like that on master-old branch. For exmple, ther is no idl folder in the root directory of the newer branches. The same relates to dlm.

**Comment by pasha-ponomarenko** [comment]
I am talking about the internal directory structure of RST.

**Comment by pasha-ponomarenko** [comment]
Oh, Keith already worte this!

**Comment by pasha-ponomarenko** [comment]
I think this is how it should be corrected now:


#export DLMPATH="${RSTPATH}/dlm"
export DLMPATH="<IDL_DEFAULT>:${RSTPATH}/codebase/superdarn/src.dlm"

# IDL environment

#export IDL_PATH="<IDL_DEFAULT>:+/${RSTPATH}/idl/lib"
export IDL_PATH="<IDL_DEFAULT>:+/${RSTPATH}/codebase/superdarn/src.idl/lib"
#export IDL_DLM_PATH="<IDL_DEFAULT>:${RSTPATH}/dlm"
export IDL_DLM_PATH="<IDL_DEFAULT>:${RSTPATH}/codebase/superdarn/src.dlm"
#export IDL_STARTUP="${RSTPATH}/idl/startup.pro"
export IDL_STARTUP="${RSTPATH}/codebase/superdarn/src.idl/startup/startup.pro"

**Comment by egthomas** [comment]
The top-level idl folder is created during compilation if your `IDL_IPATH` environment variable is set correctly and the idl_export.h file necessary for DLMs can be found.  See

https://github.com/SuperDARN/rst/blob/master/build/script/make.code#L164-L182

That was part of our fix for automatic compilation for systems without access to IDL.  If you do have IDL, step 1 of the readme instructions explicitly tells users to verify their `IDL_IPATH` environment variable.

**Comment by kkotyk** [comment]
Okay so Pasha you just need to change that line in your file and it should be fine then. Try test that out.

**Comment by pasha-ponomarenko** [comment]
Thanks Evan, it works now! 
Sorry for the hussle!

**Comment by sshepherd** [comment]
Let us all know how you are getting on with this Pasha.

**Comment by pasha-ponomarenko** [comment]
All in good time, Simon!
;-)

**Comment by sshepherd** [comment]
I was just getting worried, Pasha. We hadn't had an update in something
like 30 seconds. ;>

On Tue, Jul 25, 2017 at 3:14 PM, pasha-ponomarenko <notifications@github.com
